# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrption', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_valid_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('not_valid_after', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateExpirationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted', models.BooleanField(default=False)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enc_private_key', models.CharField(max_length=342)),
                ('public_key', models.CharField(max_length=342)),
                ('is_accepted', models.BooleanField()),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Certificate')),
                ('reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CancellationReason')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('login_date', models.DateTimeField(blank=True, null=True)),
                ('logout_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isWorking', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_private_key', models.CharField(max_length=342)),
                ('public_key', models.CharField(max_length=342)),
                ('not_valid_before_private_key', models.DateTimeField()),
                ('not_valid_after_private_key', models.DateTimeField()),
                ('not_valid_before_public_key', models.DateTimeField()),
                ('not_valid_after_public_key', models.DateTimeField()),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_topic', models.TextField()),
                ('enc_message', models.TextField()),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
        migrations.AddField(
            model_name='certificateexpirationrequest',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
        migrations.AddField(
            model_name='certificateexpirationrequest',
            name='reason_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CancellationReason'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
    ]
