# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrption', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotValidBefore', models.DateTimeField(default=django.utils.timezone.now)),
                ('NotValidAfter', models.DateTimeField()),
                ('CreationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpirationDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateExpirationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsAccepted', models.BooleanField(default=False)),
                ('DecisionDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('EncPrivateKey', models.CharField(max_length=342)),
                ('PublicKey', models.CharField(max_length=342)),
                ('IsAccepted', models.BooleanField()),
                ('DecisionDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CancellationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CertificateID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Certificate')),
                ('ReasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CancellationReason')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('PESEL', models.CharField(max_length=13, unique=True)),
                ('Address', models.CharField(max_length=50)),
                ('BirthDay', models.DateField()),
                ('CompanyEmail', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=64)),
                ('LogInDate', models.DateTimeField(null=True)),
                ('LogOutDate', models.DateTimeField(null=True)),
                ('CreationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('LastEditionDate', models.DateTimeField(null=True)),
                ('CreatedBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EncPrivateKey', models.CharField(max_length=342)),
                ('PublicKey', models.CharField(max_length=342)),
                ('NotValidBeforePrivateKey', models.DateTimeField()),
                ('NotValidAfterPrivateKey', models.DateTimeField()),
                ('NotValidBeforePublicKey', models.DateTimeField()),
                ('NotValidAfterPublicKey', models.DateTimeField()),
                ('CertificateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EncTopic', models.TextField()),
                ('EncMessage', models.TextField()),
                ('SendDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('RecipientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
                ('SenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='JobID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='LastEditedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Employee'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
        migrations.AddField(
            model_name='certificateexpirationrequest',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
        migrations.AddField(
            model_name='certificateexpirationrequest',
            name='ReasonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CancellationReason'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
    ]
