# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_isworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isWorking',
            field=models.BooleanField(default=True),
        ),
    ]
