# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_isworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateexpirationrequest',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='certificateexpirationrequest',
            name='reason_id',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='CertificateExpirationRequest',
        ),
        migrations.DeleteModel(
            name='CertificateRequest',
        ),
    ]
