# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationreason',
            old_name='descrption',
            new_name='description',
        ),
    ]
