# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171209_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='certificate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Certificate'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(),
        ),
    ]
